import { defineStore } from "pinia";

export const useProductStore = defineStore("products", {
  state: () => ({
    products: [],
  }),
  getters: {
    //get product by types
    // Men
    // Get products by type
    getProductsByType: (state) => {
      return (type) =>
        state.products.filter((product) => product.productType === type);
    },

    // getProductByTypeAndGroup: (state) => (type, group) => {
    //   console.log("Products:", state.products);
    //   console.log("Type:", type, "Group:", group);
    //   return state.products.filter(
    //     (product) =>
    //       product.productGroup === group && product.productType === type
    //   );
    // },

    getProductByTypeAndGroup: (state) => (type, group) => {
      // console.log("Products:", state.products);
      // console.log("Type:", type, "Group:", group);

      return state.products.filter((product) => {
        // Check conditions based on whether type or group is provided
        const matchesType = type ? product.productType === type : true;
        const matchesGroup = group ? product.productGroup === group : true;

        return matchesType && matchesGroup;
      });
    },

    getBestOfferProducts:
      (state) =>
      (type = null) => {
        return state.products.filter(
          (product) =>
            product.rating > 3 && (type ? product.productType === type : true)
        );
      },

    // Get best offer products (rating >= 4)
    // getBestOfferProducts: (state) => {
    //   return state.products.filter((product) => product.rating > 3);
    // },

    // getBestOfferProducts: (state) => (type) => {
    //   return state.products.filter(
    //     (product) => product.rating > 3 && product.type === type
    //   );
    // },

    // Get best-for-today products (promotionPercentage >= 20)
    getBestForTodayProducts: (state) => {
      return state.products.filter(
        (product) => product.promotionPercentage >= 20
      );
    },

    // Get Khmer Traditional products
    getKhmerTraditionalProducts: (state) => {
      return state.products.filter((product) =>
        product.productGroup.startsWith("Tradi")
      );
    },
    getAllProducts: (state) => {
      return state.products;
    },
    //  Trending banner

    // only id, name, image

    //  Trending video
    // only id, name, video
  },

  // fake fetchProducts action
  actions: {
    async fetchProducts() {
      await new Promise((resolve) => {
        setTimeout(() => {
          resolve([
            {
              productId: 1,
              productName: "T-shirt Men 1",
              productType: "Men",
              productGroup: "T-shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Comfortable cotton T-shirt",
              quantity: 0,
              rating: 4,
              promotionPercentage: 0,
              price: 100,
            },
            {
              productId: 2,
              productName: "Shirt Men 2",
              productType: "Men",
              productGroup: "Shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men2_image2.jpg",
              ],
              description: "Formal white shirt Formal white shirt",
              quantity: 30,
              rating: 4.5,
              promotionPercentage: 15,
              price: 200,
            },
            {
              productId: 3,
              productName: "Pant Men 3",
              productType: "Men",
              productGroup: "Pant",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men3_image2.jpg",
              ],
              description: "Casual blue jeans",
              quantity: 40,
              rating: 3,
              promotionPercentage: 5,
              price: 300,
            },
            {
              productId: 4,
              productName: "Towel Men 4",
              productType: "Men",
              productGroup: "Towel",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men4_image2.jpg",
              ],
              description: "Soft bath towel",
              quantity: 25,
              rating: 4,
              promotionPercentage: 20,
              price: 50,
            },
            {
              productId: 5,
              productName: "Traditional Suit Men 5",
              productType: "Men",
              productGroup: "Traditional Suit",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men5_image2.jpg",
              ],
              description: "Elegant traditional attire",
              quantity: 15,
              rating: 4.5,
              promotionPercentage: 12,
              price: 500,
            },
            {
              productId: 6,
              productName: "T-shirt Men 6",
              productType: "Men",
              productGroup: "T-shirt",
              productImages: ["Men/angkorWatT-shirt.jpg", "men6_image2.jpg"],
              description: "Graphic print T-shirt",
              quantity: 60,
              rating: 3,
              promotionPercentage: 5,
              price: 120,
            },
            {
              productId: 7,
              productName: "Shirt Men 7",
              productType: "Men",
              productGroup: "T-Shirt",
              productImages: ["Men/angkorWatT-shirt.jpg", "men7_image2.jpg"],
              description: "Slim fit office shirt",
              quantity: 20,
              rating: 4,
              promotionPercentage: 10,
              price: 220,
            },
            {
              productId: 8,
              productName: "Pant Men 8",
              productType: "Men",
              productGroup: "Pant",
              productImages: ["Men/angkorWatT-shirt.jpg", "men8_image2.jpg"],
              description: "Chino pants",
              quantity: 50,
              rating: 4.5,
              promotionPercentage: 8,
              price: 350,
            },
            {
              productId: 9,
              productName: "Towel Men 9",
              productType: "Men",
              productGroup: "Towel",
              productImages: ["Men/angkorWatT-shirt.jpg", "men9_image2.jpg"],
              description: "Large bath towel",
              quantity: 40,
              rating: 4,
              promotionPercentage: 12,
              price: 70,
            },
            {
              productId: 10,
              productName: "Traditional Men 10",
              productType: "Men",
              productGroup: "Traditional Suit",
              productImages: ["Men/angkorWatT-shirt.jpg", "men10_image2.jpg"],
              description: "Luxury formal suit",
              quantity: 12,
              rating: 4.5,
              promotionPercentage: 15,
              price: 700,
            },
            {
              productId: 11,
              productName: "T-shirt Men 11",
              productType: "Men",
              productGroup: "T-shirt",
              productImages: ["Men/angkorWatT-shirt.jpg", "men11_image2.jpg"],
              description: "Athletic workout tee",
              quantity: 70,
              rating: 3,
              promotionPercentage: 5,
              price: 130,
            },
            {
              productId: 12,
              productName: "Shirt Men 12",
              productType: "Men",
              productGroup: "Shirt",
              productImages: ["Men/AngkorWatT-shirt.jpg", "men12_image2.jpg"],
              description: "Plaid casual shirt",
              quantity: 25,
              rating: 4,
              promotionPercentage: 10,
              price: 240,
            },
            {
              productId: 13,
              productName: "Pant Men 13",
              productType: "Men",
              productGroup: "Pant",
              productImages: ["Men/angkorWatT-shirt.jpg", "men13_image2.jpg"],
              description: "Comfort fit trousers",
              quantity: 30,
              rating: 4.5,
              promotionPercentage: 7,
              price: 300,
            },
            {
              productId: 14,
              productName: "Towel Men 14",
              productType: "Men",
              productGroup: "Towel",
              productImages: ["Men/angkorWatT-shirt.jpg", "men14_image2.jpg"],
              description: "Durable travel towel",
              quantity: 35,
              rating: 3,
              promotionPercentage: 8,
              price: 60,
            },
            {
              productId: 15,
              productName: "Traditional Suit Men 15",
              productType: "Men",
              productGroup: "Traditional Suit",
              productImages: ["Men/angkorWatT-shirt.jpg", "men15_image2.jpg"],
              description: "Cultural attire",
              quantity: 20,
              rating: 4,
              promotionPercentage: 10,
              price: 550,
            },
            {
              productId: 16,
              productName: "T-shirt Men 16",
              productType: "Men",
              productGroup: "Pans",
              productImages: ["Men/angkorWatT-shirt.jpg", "men16_image2.jpg"],
              description: "Vintage graphic tee",
              quantity: 80,
              rating: 4.5,
              promotionPercentage: 12,
              price: 140,
            },
            {
              productId: 17,
              productName: "Shirt Men 17",
              productType: "Men",
              productGroup: "Shirt",
              productImages: ["Men/angkorWatT-shirt.jpg", "men17_image2.jpg"],
              description: "Classic button-down",
              quantity: 30,
              rating: 3,
              promotionPercentage: 6,
              price: 260,
            },
            {
              productId: 18,
              productName: "Pant Men 18",
              productType: "Men",
              productGroup: "Pant",
              productImages: ["Men/angkorWatT-shirt.jpg", "men18_image2.jpg"],
              description: "Stretchable formal pant",
              quantity: 40,
              rating: 4,
              promotionPercentage: 9,
              price: 400,
            },
            {
              productId: 19,
              productName: "Towel Men 19",
              productType: "Men",
              productGroup: "Towel",
              productImages: ["Men/angkorWatT-shirt.jpg", "men19_image2.jpg"],
              description: "Microfiber towel",
              quantity: 50,
              rating: 4.5,
              promotionPercentage: 10,
              price: 90,
            },
            {
              productId: 20,
              productName: "Traditional Suit Men 20",
              productType: "Men",
              productGroup: "Traditional Suit",
              productImages: ["Men/angkorWatT-shirt.jpg", "men20_image2.jpg"],
              description: "Traditional suit",
              quantity: 15,
              rating: 3,
              promotionPercentage: 11,
              price: 600,
            },

            {
              productId: 41,
              productName: "Shirt Children 1",
              productType: "Children",
              productGroup: "Shirt",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Soft cotton kids shirt",
              quantity: 50,
              rating: 4,
              promotionPercentage: 5,
              price: 80,
            },
            {
              productId: 42,
              productName: "Pant Children 2",
              productType: "Children",
              productGroup: "Pant",
              productImages: ["Children/children.jpg", "children2_image2.jpg"],
              description: "Comfortable kids pants",
              quantity: 45,
              rating: 4.5,
              promotionPercentage: 8,
              price: 90,
            },
            {
              productId: 43,
              productName: "T-shirt Children 3",
              productType: "Children",
              productGroup: "Skirt",
              productImages: ["Children/children.jpg", "children3_image2.jpg"],
              description: "Colorful T-shirt for kids",
              quantity: 60,
              rating: 4,
              promotionPercentage: 10,
              price: 70,
            },
            {
              productId: 44,
              productName: "Towel Children 4",
              productType: "Children",
              productGroup: "Towel",
              productImages: ["Children/children.jpg", "children4_image2.jpg"],
              description: "Cute kids bath towel",
              quantity: 20,
              rating: 4,
              promotionPercentage: 7,
              price: 50,
            },
            {
              productId: 45,
              productName: "Shirt Children 5",
              productType: "Children",
              productGroup: "Shirt",
              productImages: ["Children/children.jpg", "children5_image2.jpg"],
              description: "Stylish party shirt for kids",
              quantity: 30,
              rating: 3.5,
              promotionPercentage: 12,
              price: 100,
            },
            {
              productId: 46,
              productName: "Shirt Children 5",
              productType: "Children",
              productGroup: "Shirt",
              productImages: ["Children/children.jpg", "children5_image2.jpg"],
              description: "Stylish party shirt for kids",
              quantity: 30,
              rating: 4.5,
              promotionPercentage: 12,
              price: 100,
            },

            // Women
            {
              productId: 21,
              productName: "Hole Women 1",
              productType: "Women",
              productGroup: "Hat",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Stylish outfit for women",
              quantity: 60,
              rating: 4,
              promotionPercentage: 8,
              price: 120,
            },
            {
              productId: 22,
              productName: "Arvbark Women 2",
              productType: "Women",
              productGroup: "Arvbark",
              productImages: ["Women/WomenTrad.png", "women2_image2.jpg"],
              description: "Elegant traditional wear",
              quantity: 20,
              rating: 4.5,
              promotionPercentage: 10,
              price: 250,
            },
            {
              productId: 23,
              productName: "Trouser Women 3",
              productType: "Women",
              productGroup: "Skirt",
              productImages: ["Women/WomenTrad.png", "women3_image2.jpg"],
              description: "Comfortable trousers",
              quantity: 35,
              rating: 3,
              promotionPercentage: 5,
              price: 180,
            },
            {
              productId: 24,
              productName: "Skirt Women 4",
              productType: "Women",
              productGroup: "Skirt",
              productImages: ["Women/WomenTrad.png", "women4_image2.jpg"],
              description: "Chic office skirt",
              quantity: 25,
              rating: 4,
              promotionPercentage: 7,
              price: 150,
            },
            {
              productId: 25,
              productName: "Hat Women 5",
              productType: "Women",
              productGroup: "Skirt",
              productImages: ["Women/WomenTrad.png", "women5_image2.jpg"],
              description: "Fashionable summer hat",
              quantity: 10,
              rating: 4.5,
              promotionPercentage: 15,
              price: 90,
            },
            {
              productId: 26,
              productName: "Shirt Women 6",
              productType: "Women",
              productGroup: "Shirt",
              productImages: ["Women/WomenTrad.png", "women6_image2.jpg"],
              description: "Soft fabric shirt",
              quantity: 50,
              rating: 3,
              promotionPercentage: 5,
              price: 100,
            },
            {
              productId: 27,
              productName: "Traditional Dress Women 7",
              productType: "Women",
              productGroup: "Traditional Dress",
              productImages: ["Women/WomenTrad.png", "women7_image2.jpg"],
              description: "Cultural attire for events",
              quantity: 30,
              rating: 4,
              promotionPercentage: 10,
              price: 400,
            },
            {
              productId: 28,
              productName: "Hat Women 8",
              productType: "Women",
              productGroup: "Hat",
              productImages: ["Women/WomenTrad.png", "women8_image2.jpg"],
              description: "Elegant wide-brimmed hat",
              quantity: 20,
              rating: 4.5,
              promotionPercentage: 8,
              price: 130,
            },
            {
              productId: 29,
              productName: "Trouser Women 9",
              productType: "Women",
              productGroup: "Trouser",
              productImages: ["Women/WomenTrad.png", "women9_image2.jpg"],
              description: "High-waisted trousers",
              quantity: 45,
              rating: 3,
              promotionPercentage: 12,
              price: 210,
            },
            {
              productId: 30,
              productName: "Arvbark Women 10",
              productType: "Women",
              productGroup: "Arvbark",
              productImages: ["Women/WomenTrad.png", "women10_image2.jpg"],
              description: "Classic outfit",
              quantity: 15,
              rating: 4.5,
              promotionPercentage: 10,
              price: 300,
            },
            {
              productId: 30,
              productName: "Arvbark Women 10",
              productType: "Women",
              productGroup: "Skirt",
              productImages: ["Women/WomenTrad.png", "women10_image2.jpg"],
              description: "Classic outfit",
              quantity: 15,
              rating: 4.5,
              promotionPercentage: 10,
              price: 300,
            },
            {
              productId: 50,
              productName: "Classic Shirt",
              productType: "Men",
              productGroup: "Shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "A stylish classic shirt for men.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 10,
              price: 25,
            },
            {
              productId: 51,
              productName: "Summer T-shirt",
              productType: "Women",
              productGroup: "T-shirt",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Soft and breezy summer T-shirt.",
              quantity: 0,
              rating: 5,
              promotionPercentage: 0,
              price: 15,
            },
            {
              productId: 52,
              productName: "Basic White Shirt",
              productType: "Men",
              productGroup: "Shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "A basic, essential white shirt.",
              quantity: 0,
              rating: 3,
              promotionPercentage: 5,
              price: 20,
            },
            {
              productId: 53,
              productName: "Floral Summer Dress",
              productType: "Women",
              productGroup: "Dress",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Floral patterned summer dress for women.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 15,
              price: 30,
            },
            {
              productId: 54,
              productName: "Casual Polo",
              productType: "Men",
              productGroup: "Polo",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Casual yet stylish polo shirt for men.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 0,
              price: 22,
            },
            {
              productId: 55,
              productName: "Graphic T-shirt",
              productType: "Men",
              productGroup: "T-shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Trendy graphic T-shirt with unique designs.",
              quantity: 0,
              rating: 3,
              promotionPercentage: 10,
              price: 18,
            },
            {
              productId: 56,
              productName: "Slim Fit Jeans",
              productType: "Men",
              productGroup: "Jeans",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Slim fit jeans for a modern, sleek look.",
              quantity: 0,
              rating: 5,
              promotionPercentage: 20,
              price: 35,
            },
            {
              productId: 57,
              productName: "Linen Blouse",
              productType: "Women",
              productGroup: "Blouse",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "A light and breathable linen blouse.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 10,
              price: 28,
            },
            {
              productId: 58,
              productName: "Denim Jacket",
              productType: "Women",
              productGroup: "Jacket",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Classic denim jacket for stylish layering.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 5,
              price: 50,
            },
            {
              productId: 59,
              productName: "Chino Shorts",
              productType: "Men",
              productGroup: "Shorts",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Comfortable chino shorts for men.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 15,
              price: 25,
            },
            {
              productId: 60,
              productName: "Cotton Hoodie",
              productType: "Men",
              productGroup: "Hoodie",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Soft cotton hoodie for cozy days.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 10,
              price: 35,
            },
            {
              productId: 61,
              productName: "Summer Tunic",
              productType: "Women",
              productGroup: "Tunic",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Breezy summer tunic perfect for warm days.",
              quantity: 0,
              rating: 5,
              promotionPercentage: 0,
              price: 22,
            },
            {
              productId: 62,
              productName: "V-neck Sweater",
              productType: "Men",
              productGroup: "Sweater",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Casual V-neck sweater for versatile styling.",
              quantity: 0,
              rating: 5,
              promotionPercentage: 20,
              price: 40,
            },
            {
              productId: 63,
              productName: "Ripped Jeans",
              productType: "Women",
              productGroup: "Jeans",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Trendy ripped jeans with a modern fit.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 10,
              price: 45,
            },
            {
              productId: 64,
              productName: "Winter Coat",
              productType: "Men",
              productGroup: "Coat",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Warm winter coat for cold weather protection.",
              quantity: 0,
              rating: 3,
              promotionPercentage: 0,
              price: 75,
            },
            {
              productId: 65,
              productName: "Boho Maxi Dress",
              productType: "Women",
              productGroup: "Dress",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "A flowing bohemian-inspired maxi dress.",
              quantity: 0,
              rating: 5,
              promotionPercentage: 15,
              price: 50,
            },
            {
              productId: 66,
              productName: "Zip-up Hoodie",
              productType: "Women",
              productGroup: "Hoodie",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Zip-up hoodie for casual and comfortable wear.",
              quantity: 0,
              rating: 3,
              promotionPercentage: 10,
              price: 35,
            },
            {
              productId: 67,
              productName: "Cropped Sweatshirt",
              productType: "Men",
              productGroup: "Sweatshirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Trendy cropped sweatshirt for men.",
              quantity: 0,
              rating: 4,
              promotionPercentage: 5,
              price: 30,
            },

            {
              productId: 66,
              productName: "Casual Shirt",
              productType: "Men",
              productGroup: "Shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Comfortable casual shirt for everyday wear.",
              quantity: 10,
              rating: 4,
              promotionPercentage: 10,
              price: 30,
            },
            {
              productId: 67,
              productName: "Silk Blouse",
              productType: "Women",
              productGroup: "Blouse",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Elegant silk blouse for formal occasions.",
              quantity: 15,
              rating: 5,
              promotionPercentage: 20,
              price: 40,
            },
            {
              productId: 68,
              productName: "Kids T-Shirt",
              productType: "Children",
              productGroup: "Shirt",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Bright and colorful T-shirt for kids.",
              quantity: 25,
              rating: 4,
              promotionPercentage: 5,
              price: 15,
            },
            {
              productId: 69,
              productName: "Formal Pants",
              productType: "Men",
              productGroup: "Pants",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Stylish formal pants for office wear.",
              quantity: 8,
              rating: 3,
              promotionPercentage: 0,
              price: 50,
            },
            {
              productId: 70,
              productName: "Summer Dress",
              productType: "Women",
              productGroup: "Dress",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Light and breezy summer dress.",
              quantity: 12,
              rating: 5,
              promotionPercentage: 10,
              price: 35,
            },
            {
              productId: 71,
              productName: "Kids Shorts",
              productType: "Children",
              productGroup: "Short-pants",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Durable shorts for active kids.",
              quantity: 20,
              rating: 4,
              promotionPercentage: 5,
              price: 12,
            },
            {
              productId: 72,
              productName: "Wool Scarf",
              productType: "Men",
              productGroup: "Krama",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Warm and stylish wool scarf.",
              quantity: 10,
              rating: 5,
              promotionPercentage: 15,
              price: 25,
            },
            {
              productId: 73,
              productName: "Elegant Accessories",
              productType: "Women",
              productGroup: "Accessories",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Premium accessories to enhance your look.",
              quantity: 30,
              rating: 5,
              promotionPercentage: 10,
              price: 60,
            },
            {
              productId: 74,
              productName: "Kids Sneakers",
              productType: "Children",
              productGroup: "Shoes",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Comfortable and durable sneakers for kids.",
              quantity: 18,
              rating: 4,
              promotionPercentage: 10,
              price: 20,
            },
            {
              productId: 75,
              productName: "Denim Jacket",
              productType: "Men",
              productGroup: "Coat",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Trendy denim jacket for casual outings.",
              quantity: 5,
              rating: 3,
              promotionPercentage: 5,
              price: 60,
            },

            {
              productId: 76,
              productName: "Floral Skirt",
              productType: "Women",
              productGroup: "Sampot (Skirt)",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Beautiful floral skirt for summer.",
              quantity: 15,
              rating: 4,
              promotionPercentage: 10,
              price: 25,
            },
            {
              productId: 77,
              productName: "Kids Winter Coat",
              productType: "Children",
              productGroup: "Coat",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Warm coat for children during winter.",
              quantity: 8,
              rating: 5,
              promotionPercentage: 20,
              price: 40,
            },
            {
              productId: 78,
              productName: "Leather Belt",
              productType: "Men",
              productGroup: "Accessories",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Durable leather belt for daily use.",
              quantity: 20,
              rating: 5,
              promotionPercentage: 10,
              price: 15,
            },
            {
              productId: 79,
              productName: "Classic Necklace",
              productType: "Women",
              productGroup: "Accessories",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Elegant necklace with a timeless design.",
              quantity: 10,
              rating: 5,
              promotionPercentage: 20,
              price: 50,
            },
            {
              productId: 80,
              productName: "Kids Hat",
              productType: "Children",
              productGroup: "Hats",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Protective hat for sunny days.",
              quantity: 12,
              rating: 4,
              promotionPercentage: 5,
              price: 10,
            },
            {
              productId: 81,
              productName: "Cotton T-Shirt",
              productType: "Men",
              productGroup: "T-shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Soft and breathable cotton T-shirt.",
              quantity: 25,
              rating: 4,
              promotionPercentage: 10,
              price: 20,
            },
            {
              productId: 82,
              productName: "Summer Hat",
              productType: "Women",
              productGroup: "Hats",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Wide-brim hat for summer outings.",
              quantity: 8,
              rating: 5,
              promotionPercentage: 15,
              price: 30,
            },
            {
              productId: 83,
              productName: "Kids Backpack",
              productType: "Children",
              productGroup: "Accessories",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Colorful backpack for school kids.",
              quantity: 15,
              rating: 4,
              promotionPercentage: 10,
              price: 18,
            },
            {
              productId: 84,
              productName: "Knitted Sweater",
              productType: "Men",
              productGroup: "Coat",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Comfortable knitted sweater for cold weather.",
              quantity: 6,
              rating: 4,
              promotionPercentage: 5,
              price: 45,
            },
            {
              productId: 85,
              productName: "Pearl Earrings",
              productType: "Women",
              productGroup: "Accessories",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Elegant pearl earrings for special occasions.",
              quantity: 5,
              rating: 5,
              promotionPercentage: 25,
              price: 35,
            },
            {
              productId: 101,
              productName: "Av Pak (traditional silk shirt)",
              productType: "Men",
              productGroup: "Shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Elegant silk shirt for traditional occasions.",
              quantity: 10,
              rating: 4,
              promotionPercentage: 10,
              price: 60,
            },
            {
              productId: 102,
              productName: "Casual short-sleeve Khmer T-shirts",
              productType: "Men",
              productGroup: "T-shirt",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description:
                "Comfortable casual T-shirts with unique Khmer designs.",
              quantity: 15,
              rating: 5,
              promotionPercentage: 5,
              price: 25,
            },
            {
              productId: 103,
              productName: "Silk Sampot trousers",
              productType: "Men",
              productGroup: "Pants",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Traditional trousers made of high-quality silk.",
              quantity: 12,
              rating: 5,
              promotionPercentage: 15,
              price: 70,
            },
            {
              productId: 104,
              productName: "Kbang (traditional Khmer hat)",
              productType: "Men",
              productGroup: "Hats",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description:
                "Classic traditional hat for ceremonies and casual wear.",
              quantity: 8,
              rating: 4,
              promotionPercentage: 0,
              price: 15,
            },
            {
              productId: 105,
              productName: "Classic checkered Krama scarf",
              productType: "Men",
              productGroup: "Krama",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Versatile scarf for casual and traditional use.",
              quantity: 20,
              rating: 5,
              promotionPercentage: 10,
              price: 10,
            },
            {
              productId: 106,
              productName: "Casual cotton shorts",
              productType: "Men",
              productGroup: "Short-pants",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description: "Comfortable shorts for everyday wear.",
              quantity: 25,
              rating: 4,
              promotionPercentage: 5,
              price: 20,
            },
            {
              productId: 107,
              productName: "Leather sandals",
              productType: "Men",
              productGroup: "Shoes",
              productImages: [
                "Men/angkorWatT-shirt.jpg",
                "Men/men1_image2.jpg",
              ],
              description:
                "Durable leather sandals for outdoor and casual use.",
              quantity: 18,
              rating: 4,
              promotionPercentage: 0,
              price: 30,
            },
            {
              productId: 108,
              productName:
                "Av Pak for women (silk blouse with detailed embroidery)",
              productType: "Women",
              productGroup: "Blouse",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Elegant silk blouse for formal occasions.",
              quantity: 14,
              rating: 5,
              promotionPercentage: 20,
              price: 65,
            },
            {
              productId: 109,
              productName: "Sampot Hol (silk, patterned)",
              productType: "Women",
              productGroup: "Sampot (Skirt)",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Beautifully patterned silk skirt for formal wear.",
              quantity: 10,
              rating: 5,
              promotionPercentage: 10,
              price: 75,
            },
            {
              productId: 110,
              productName: "Cambodian traditional silk dresses",
              productType: "Women",
              productGroup: "Dress",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Elegant dress for weddings and celebrations.",
              quantity: 5,
              rating: 5,
              promotionPercentage: 15,
              price: 90,
            },
            {
              productId: 111,
              productName: "Silk Krama (formal wear)",
              productType: "Women",
              productGroup: "Scarf (Krama)",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Stylish silk scarf for formal and casual use.",
              quantity: 20,
              rating: 5,
              promotionPercentage: 5,
              price: 20,
            },
            {
              productId: 112,
              productName: "Silver or gold brooches",
              productType: "Women",
              productGroup: "Accessories",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description:
                "Ornamental brooches for traditional and modern attire.",
              quantity: 12,
              rating: 4,
              promotionPercentage: 10,
              price: 40,
            },
            {
              productId: 113,
              productName: "Khmer-style sandals",
              productType: "Women",
              productGroup: "Shoes",
              productImages: ["Women/WomenTrad.png", "women1_image2.jpg"],
              description: "Traditional sandals with modern comfort.",
              quantity: 15,
              rating: 4,
              promotionPercentage: 0,
              price: 25,
            },
            {
              productId: 114,
              productName:
                "Mini Av Pak (traditional shirts for boys and girls)",
              productType: "Children",
              productGroup: "Shirt",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Traditional shirts designed for kids.",
              quantity: 8,
              rating: 4,
              promotionPercentage: 5,
              price: 15,
            },
            {
              productId: 115,
              productName: "Small silk Sampot trousers",
              productType: "Children",
              productGroup: "Pants",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Comfortable trousers made from silk for children.",
              quantity: 10,
              rating: 4,
              promotionPercentage: 10,
              price: 25,
            },
            {
              productId: 116,
              productName: "Mini Sampot Hol dresses for girls",
              productType: "Children",
              productGroup: "Dresses",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Elegant dresses for young girls.",
              quantity: 5,
              rating: 5,
              promotionPercentage: 10,
              price: 30,
            },
            {
              productId: 117,
              productName: "Lightweight cotton Krama for casual use",
              productType: "Children",
              productGroup: "Krama",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Simple cotton Krama for everyday use.",
              quantity: 12,
              rating: 4,
              promotionPercentage: 5,
              price: 8,
            },
            {
              productId: 118,
              productName: "Child-friendly Khmer sandals",
              productType: "Children",
              productGroup: "Shoes",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Comfortable and durable sandals for kids.",
              quantity: 18,
              rating: 5,
              promotionPercentage: 0,
              price: 15,
            },
            {
              productId: 119,
              productName: "Small ornamental belts",
              productType: "Children",
              productGroup: "Accessories",
              productImages: ["Children/children.jpg", "children1_image2.jpg"],
              description: "Cute belts for children to accessorize outfits.",
              quantity: 10,
              rating: 4,
              promotionPercentage: 10,
              price: 10,
            },
          ]);
        }, 30);
      }).then((products) => (this.products = products));
    },
  },
});
